# Generated by Django 3.0.8 on 2020-07-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200715_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='month',
            new_name='status',
        ),
    ]
