# Generated by Django 3.0.8 on 2020-07-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='On Queue', max_length=9),
        ),
    ]
